<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.nguiland</groupId>
  <artifactId>nguiland-dependencies</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>pom</packaging>
  <name>nguiland-dependencies</name>
  <description>Parent pom providing dependency and plugin management</description>
  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.release>17</maven.compiler.release>
    <maven-clean-plugin.version>3.3.2</maven-clean-plugin.version>
    <maven-resources-plugin.version>3.3.0</maven-resources-plugin.version>
    <maven-compiler-plugin.version>3.10.1</maven-compiler-plugin.version>
    <maven-surefire-plugin.version>3.1.2</maven-surefire-plugin.version>
    <maven-jar-plugin.version>3.1.0</maven-jar-plugin.version>
    <maven-install-plugin.version>3.1.0</maven-install-plugin.version>
    <maven-deploy-plugin.version>3.1.0</maven-deploy-plugin.version>
    <maven-site-plugin.version>3.12.1</maven-site-plugin.version>
    <maven-project-info-reports-plugin.version>3.6.2</maven-project-info-reports-plugin.version>
    <jacoco.version>0.8.13</jacoco.version>
    <spring-boot.version>3.5.7</spring-boot.version>
    <spring-cloud.version>2025.0.0</spring-cloud.version>
    <nguiland-io-utils.version>0.0.1-SNAPSHOT</nguiland-io-utils.version>
    <nguiland-web-oauth2.version>0.0.1-SNAPSHOT</nguiland-web-oauth2.version>
    <nguiland-security-test.version>0.0.1-SNAPSHOT</nguiland-security-test.version>
    <nguiland-rest.version>0.0.1-SNAPSHOT</nguiland-rest.version>
    <nguiland-data-validation.version>0.0.1-SNAPSHOT</nguiland-data-validation.version>
    <nguiland-orm.version>0.0.1-SNAPSHOT</nguiland-orm.version>
  </properties>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-dependencies</artifactId>
        <version>${spring-boot.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>

      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-dependencies</artifactId>
        <version>${spring-cloud.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>

      <dependency>
        <groupId>org.nguiland.io</groupId>
        <artifactId>nguiland-io-utils</artifactId>
        <version>${nguiland-io-utils.version}</version>
      </dependency>
      <dependency>
        <groupId>org.nguiland.security</groupId>
        <artifactId>nguiland-web-oauth2</artifactId>
        <version>${nguiland-web-oauth2.version}</version>
      </dependency>
      <dependency>
        <groupId>org.nguiland.security</groupId>
        <artifactId>nguiland-security-test</artifactId>
        <version>${nguiland-security-test.version}</version>
      </dependency>
      <dependency>
        <groupId>org.nguiland.rest</groupId>
        <artifactId>nguiland-rest</artifactId>
        <version>${nguiland-rest.version}</version>
      </dependency>
      <dependency>
        <groupId>org.nguiland.data</groupId>
        <artifactId>nguiland-data-validation</artifactId>
        <version>${nguiland-data-validation.version}</version>
      </dependency>
      <dependency>
        <groupId>org.nguiland.data</groupId>
        <artifactId>nguiland-orm</artifactId>
        <version>${nguiland-orm.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <build>
    <pluginManagement><!-- lock down plugins versions to avoid using Maven defaults (may be moved to
      parent pom) -->
      <plugins>
        <!-- clean lifecycle, see
        https://maven.apache.org/ref/current/maven-core/lifecycles.html#clean_Lifecycle -->
        <plugin>
          <artifactId>maven-clean-plugin</artifactId>
          <version>${maven-clean-plugin.version}</version>
        </plugin>
        <!-- default lifecycle, jar packaging: see
        https://maven.apache.org/ref/current/maven-core/default-bindings.html#Plugin_bindings_for_jar_packaging -->
        <plugin>
          <artifactId>maven-resources-plugin</artifactId>
          <version>${maven-resources-plugin.version}</version>
        </plugin>
        <plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>${maven-compiler-plugin.version}</version>
        </plugin>
        <plugin>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>${maven-surefire-plugin.version}</version>
        </plugin>
        <plugin>
          <artifactId>maven-jar-plugin</artifactId>
          <version>${maven-jar-plugin.version}</version>
        </plugin>
        <plugin>
          <artifactId>maven-install-plugin</artifactId>
          <version>${maven-install-plugin.version}</version>
        </plugin>
        <plugin>
          <artifactId>maven-deploy-plugin</artifactId>
          <version>${maven-deploy-plugin.version}</version>
        </plugin>
        <!-- site lifecycle, see
        https://maven.apache.org/ref/current/maven-core/lifecycles.html#site_Lifecycle -->
        <plugin>
          <artifactId>maven-site-plugin</artifactId>
          <version>${maven-site-plugin.version}</version>
        </plugin>
        <plugin>
          <artifactId>maven-project-info-reports-plugin</artifactId>
          <version>${maven-project-info-reports-plugin.version}</version>
        </plugin>

        <plugin>
          <groupId>org.jacoco</groupId>
          <artifactId>jacoco-maven-plugin</artifactId>
          <version>${jacoco.version}</version>
          <executions>
            <execution>
              <id>jacoco-initialize</id>
              <goals>
                <goal>prepare-agent</goal>
              </goals>
            </execution>
            <execution>
              <id>jacoco-site</id>
              <phase>package</phase>
              <goals>
                <goal>report</goal>
              </goals>
            </execution>
          </executions>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
</project>